version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: db_1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mjc_db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "mjc_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    container_name: web_1
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: mjc_db
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
