# Generated by Django 5.1.6 on 2025-03-11 10:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageacceuil',
            name='flash_message',
        ),
        migrations.AddField(
            model_name='pageacceuil',
            name='extra_content',
            field=wagtail.fields.RichTextField(blank=True, help_text="Message spécial à en dessous de la section d'introduction", null=True, verbose_name='Contenu optionnel'),
        ),
    ]
