# Generated by Django 5.1.6 on 2025-02-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='PageDAcceuil',
        ),
    ]
