# Generated by Django 5.1.6 on 2025-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageacceuil',
            name='intro_title',
            field=models.CharField(default='Bienvenue à la MJC', max_length=255, verbose_name="Titre d'introduction"),
        ),
    ]
