# Generated by Django 5.1.7 on 2025-03-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_pageacceuil_flash_message_and_more'),
        ('wagtailcore', '0095_query_searchpromotion_querydailyhits'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageAcceuil',
            new_name='PageAccueil',
        ),
    ]
