# Generated by Django 5.1.6 on 2025-02-19 16:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_homepage_pagedacceuil'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagedacceuil',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.AddField(
            model_name='pagedacceuil',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête"),
        ),
        migrations.AddField(
            model_name='pagedacceuil',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Texte d'introduction"),
        ),
        migrations.AddField(
            model_name='pagedacceuil',
            name='intro_title',
            field=models.CharField(blank=True, max_length=100, verbose_name="Titre d'introduction"),
        ),
    ]
