# Generated by Django 5.1.7 on 2025-04-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_pageacceuil_pageaccueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaccueil',
            name='intro_subtitle',
            field=models.CharField(default='Ici, on vous propose', max_length=255, verbose_name="Sous-titre d'introduction"),
        ),
    ]
