# Generated by Django 5.1.6 on 2025-02-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pagedacceuil_options_pagedacceuil_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedacceuil',
            name='rotating_words',
            field=models.CharField(default='Modern,Creative,Lifestyle', help_text='Mots à faire tourner, séparés par des virgules', max_length=255, verbose_name='Mots rotatifs'),
        ),
    ]
