# Generated by Django 5.1.6 on 2025-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pageacceuil_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageacceuil',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés spécifiques à cette page séparés par des virgules', max_length=255),
        ),
    ]
