# Generated by Django 5.1.6 on 2025-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_pageacceuil_seo_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageacceuil',
            name='flash_message',
            field=models.CharField(blank=True, help_text='Message spécial à afficher en haut de la page', max_length=255, null=True, verbose_name='Message flash'),
        ),
    ]
