# Generated by Django 5.1.6 on 2025-02-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pagedacceuil_rotating_words'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagedacceuil',
            name='rotating_words',
        ),
        migrations.AlterField(
            model_name='pagedacceuil',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête"),
        ),
        migrations.AlterField(
            model_name='pagedacceuil',
            name='intro_title',
            field=models.CharField(max_length=100, verbose_name="Titre d'introduction"),
        ),
        migrations.CreateModel(
            name='RotatingWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Mot rotatif')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotating_words', to='home.pagedacceuil')),
            ],
            options={
                'verbose_name': 'Mot rotatif',
                'verbose_name_plural': 'Mots rotatifs',
            },
        ),
    ]
