# Generated by Django 5.1.6 on 2025-03-06 15:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pageacceuil_flash_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageacceuil',
            name='flash_message',
            field=wagtail.fields.RichTextField(blank=True, help_text="Message spécial à en dessous de la section d'introduction", null=True, verbose_name='Message flash'),
        ),
    ]
