# Generated by Django 5.1.7 on 2025-04-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pageaccueil_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageaccueil',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='pageaccueil',
            name='ville',
        ),
    ]
