# Generated by Django 5.1.6 on 2025-02-20 10:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_pagedacceuil_rotating_words_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagedacceuil',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rotatingword',
            options={},
        ),
        migrations.RemoveField(
            model_name='pagedacceuil',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='rotatingword',
            name='text',
        ),
        migrations.AddField(
            model_name='rotatingword',
            name='word',
            field=models.CharField(default="de l'Art", max_length=255),
        ),
        migrations.AlterField(
            model_name='pagedacceuil',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pagedacceuil',
            name='intro_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rotatingword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rotatingword',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotating_words', to='home.pagedacceuil'),
        ),
    ]
