# Generated by Django 5.1.6 on 2025-02-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pagedacceuil_hero_type_pagedacceuil_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagedacceuil',
            name='hero_type',
        ),
        migrations.RemoveField(
            model_name='pagedacceuil',
            name='video_url',
        ),
    ]
