# Generated by Django 5.1.6 on 2025-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_pagedacceuil_hero_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedacceuil',
            name='video_url',
            field=models.URLField(blank=True, help_text="Collez l'URL de la vidéo YouTube (format embed)", null=True, verbose_name='URL de la vidéo YouTube'),
        ),
    ]
