# Generated by Django 5.1.6 on 2025-03-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pagedacceuil_seo_keywords'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageDAcceuil',
            new_name='PageAcceuil',
        ),
    ]
