# Generated by Django 5.1.6 on 2025-03-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_pagedacceuil_pageacceuil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageacceuil',
            options={'verbose_name': "Page d'Accueil"},
        ),
    ]
