# Generated by Django 5.1.6 on 2025-03-06 10:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_hours_content', wagtail.fields.RichTextField(blank=True, verbose_name='Horaires période scolaire')),
                ('vacation_hours_content', wagtail.fields.RichTextField(blank=True, verbose_name='Horaires période vacances')),
                ('extra', models.CharField(blank=True, max_length=255, verbose_name='Message en extra (optionnel)')),
            ],
            options={
                'verbose_name': 'Paramètres du pied de page',
            },
        ),
    ]
