# Generated by Django 5.1.6 on 2025-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=255, verbose_name='Jour(s)')),
                ('hours', models.CharField(max_length=255, verbose_name='Horaires')),
            ],
            options={
                'verbose_name': 'Paramètres du pied de page',
            },
        ),
    ]
