# Generated by Django 5.1.6 on 2025-03-05 16:42

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='days',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='hours',
        ),
        migrations.CreateModel(
            name='SchoolHoursEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=255, verbose_name='Jour(s)')),
                ('hours', models.CharField(max_length=255, verbose_name='Horaires')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_hours', to='common.footersettings')),
            ],
        ),
        migrations.CreateModel(
            name='VacationHoursEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=255, verbose_name='Jour(s)')),
                ('hours', models.CharField(max_length=255, verbose_name='Horaires')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_hours', to='common.footersettings')),
            ],
        ),
    ]
