# Generated by Django 5.1.6 on 2025-03-10 09:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', wagtail.fields.RichTextField(blank=True, help_text="Jusqu'à 100 caractères", null=True)),
                ('show', models.BooleanField(default=False, verbose_name='Montrer')),
            ],
            options={
                'verbose_name': 'Message Flash',
            },
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Informations du Pied de page'},
        ),
    ]
