# Generated by Django 5.1.6 on 2025-03-10 10:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='carnon_extra',
            field=models.CharField(blank=True, max_length=255, verbose_name='Message en extra Carnon (optionnel)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='carnon_school_hours_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Horaires période scolaire Carnon'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='carnon_vacation_hours_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Horaires période vacances Carnon'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='extra',
            field=models.CharField(blank=True, max_length=255, verbose_name='Message en extra Mauguio (optionnel)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='school_hours_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Horaires période scolaire Mauguio'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='vacation_hours_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Horaires période vacances Mauguio'),
        ),
    ]
