# Generated by Django 5.1.6 on 2025-03-05 17:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_footersettings_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationhoursentry',
            name='settings',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='extra',
            field=models.CharField(blank=True, max_length=255, verbose_name='Message en extra (optionnel)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='school_hours_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Horaires période scolaire'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='vacation_hours_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Horaires période vacances'),
        ),
        migrations.DeleteModel(
            name='SchoolHoursEntry',
        ),
        migrations.DeleteModel(
            name='VacationHoursEntry',
        ),
    ]
