# Generated by Django 5.1.6 on 2025-03-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_footersettings_carnon_extra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersettings',
            old_name='carnon_school_hours_content',
            new_name='carnon_school_schedule',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='carnon_vacation_hours_content',
            new_name='carnon_vacation_schedule',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='school_hours_content',
            new_name='school_schedule',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='vacation_hours_content',
            new_name='vacation_schedule',
        ),
    ]
