# Generated by Django 5.1.6 on 2025-03-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_themesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'Thème de couleurs'},
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_primary_light',
        ),
    ]
