# Generated by Django 5.1.6 on 2025-03-12 10:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_themesettings_color_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='color_primary',
            field=colorfield.fields.ColorField(blank=True, default='#20223B', image_field=None, max_length=7, samples=None, verbose_name='Couleur primaire (en hexadécimal)'),
        ),
    ]
