# Generated by Django 5.1.6 on 2025-03-12 10:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_themesettings_color_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='color_primary',
            field=colorfield.fields.ColorField(default='#20223B', image_field=None, max_length=25, samples=None, verbose_name='Couleur primaire (en hexadécimal)'),
        ),
    ]
