# Generated by Django 5.1.6 on 2025-03-12 11:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_themesettings_color_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashmessage',
            name='message',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
