# Generated by Django 5.1.6 on 2025-03-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_baseindexpage_image_alter_detailpage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseindexpage',
            options={'verbose_name': 'Page liste des sous-pages'},
        ),
    ]
