# Generated by Django 5.1.7 on 2025-04-04 08:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_baseindexpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseindexpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='detailpage',
            name='show_image_in_page',
            field=models.BooleanField(default=True, help_text="Décochez pour afficher l'image uniquement dans la grille de la page parente", verbose_name="Afficher l'image dans la page"),
        ),
    ]
