# Generated by Django 5.1.7 on 2025-04-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_baseindexpage_content_detailpage_show_image_in_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseindexpage',
            name='ville',
            field=models.CharField(blank=True, choices=[('Mauguio', 'Mauguio'), ('Carnon', 'Carnon'), ('Mauguio et Carnon', 'Mauguio et Carnon')], default='Mauguio', max_length=17),
        ),
        migrations.AddField(
            model_name='detailpage',
            name='ville',
            field=models.CharField(blank=True, choices=[('Mauguio', 'Mauguio'), ('Carnon', 'Carnon'), ('Mauguio et Carnon', 'Mauguio et Carnon')], default='Mauguio', max_length=17),
        ),
    ]
