# Generated by Django 5.1.7 on 2025-04-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_baseindexpage_ville_detailpage_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseindexpage',
            name='ville',
            field=models.CharField(blank=True, choices=[('Mauguio', 'Mauguio'), ('Carnon', 'Carnon'), ('Mauguio et Carnon', 'Mauguio et Carnon')], max_length=17),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='ville',
            field=models.CharField(blank=True, choices=[('Mauguio', 'Mauguio'), ('Carnon', 'Carnon'), ('Mauguio et Carnon', 'Mauguio et Carnon')], max_length=17),
        ),
    ]
