# Generated by Django 5.1.6 on 2025-03-06 14:04

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords specific to this page', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu')),
            ],
            options={
                'verbose_name': "Grille pages de l'Association",
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='AssociationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords specific to this page', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Sous-titre')),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu')),
                ('show_image_in_page', models.BooleanField(default=True, help_text="Décochez pour afficher l'image uniquement dans la grille de la page parente", verbose_name="Afficher l'image dans la page")),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Page Association',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
