# Generated by Django 5.1.6 on 2025-02-21 13:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
            ],
            options={
                'verbose_name': "Page d'index de l'Association",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AssociationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Sous-titre')),
                ('body', wagtail.fields.RichTextField(verbose_name='Contenu')),
                ('card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': "Page de l'Association",
            },
            bases=('wagtailcore.page',),
        ),
    ]
