# Generated by Django 5.1.6 on 2025-03-10 10:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationIndexPage',
            fields=[
                ('baseindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.baseindexpage')),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu')),
            ],
            options={
                'verbose_name': "Grille pages de l'Association",
            },
            bases=('common.baseindexpage', models.Model),
        ),
        migrations.CreateModel(
            name='AssociationPage',
            fields=[
                ('detailpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.detailpage')),
                ('show_image_in_page', models.BooleanField(default=True, help_text="Décochez pour afficher l'image uniquement dans la grille de la page parente", verbose_name="Afficher l'image dans la page")),
            ],
            options={
                'verbose_name': 'Page Association',
            },
            bases=('common.detailpage',),
        ),
    ]
