# Generated by Django 5.1.6 on 2025-02-21 14:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationindexpage',
            options={'verbose_name': "Grille pages de l'Association"},
        ),
        migrations.RemoveField(
            model_name='associationindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='associationindexpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='associationpage',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text="Cette image sera utilisée pour la vignette dans la page d'index", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
    ]
