# Generated by Django 5.1.6 on 2025-02-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_alter_associationindexpage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationpage',
            name='card_image_link',
            field=models.URLField(blank=True, help_text="Lien optionnel lors du clic sur l'image", verbose_name="Lien de l'image"),
        ),
        migrations.AddField(
            model_name='associationpage',
            name='card_images',
            field=models.ManyToManyField(blank=True, help_text='Ces images seront utilisées dans la galerie', related_name='+', to='wagtailimages.image', verbose_name='Images'),
        ),
    ]
