# Generated by Django 5.1.6 on 2025-02-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_associationpage_card_image_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationpage',
            name='card_image_link',
        ),
        migrations.RemoveField(
            model_name='associationpage',
            name='card_images',
        ),
        migrations.AlterField(
            model_name='associationpage',
            name='card_image',
            field=models.CharField(blank=True, help_text='Vous pouvez soit télécharger une image, soit fournir un lien URL vers une image', max_length=500, null=True, verbose_name='Image'),
        ),
    ]
