# Generated by Django 5.1.6 on 2025-02-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_remove_associationpage_card_image_link_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationpage',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text="Cette image sera utilisée pour la vignette dans la page d'index", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
    ]
