# Generated by Django 5.1.6 on 2025-02-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_alter_associationpage_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationpage',
            name='show_image_in_page',
            field=models.BooleanField(default=True, help_text="Décochez pour afficher l'image uniquement dans la grille", verbose_name="Afficher l'image dans la page"),
        ),
    ]
