# Generated by Django 5.1.6 on 2025-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_associationpage_show_image_in_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationpage',
            name='show_image_in_page',
            field=models.BooleanField(default=True, help_text="Décochez pour afficher l'image uniquement dans la grille de la page parente", verbose_name="Afficher l'image dans la page"),
        ),
    ]
