# Generated by Django 5.1.6 on 2025-02-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_alter_associationpage_show_image_in_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associationpage',
            old_name='card_image',
            new_name='image',
        ),
    ]
