# Generated by Django 5.1.6 on 2025-02-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_remove_associationpage_body_associationpage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationpage',
            options={'verbose_name': 'Page Association'},
        ),
    ]
