# Generated by Django 5.1.6 on 2025-02-27 16:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_alter_associationpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Contenu'),
        ),
    ]
