# Generated by Django 5.1.6 on 2025-03-10 10:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_keywords', models.CharField(blank=True, help_text='Mots-clés spécifiques à cette page séparés par des virgules', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Liste des Activités',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
