# Generated by Django 5.1.6 on 2025-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='link',
            field=models.URLField(blank=True, help_text='Lien de redirection pour le bouton'),
        ),
        migrations.AlterField(
            model_name='activitypage',
            name='price_non_resident',
            field=models.CharField(help_text='Prix pour les non-résidents', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitypage',
            name='price_resident',
            field=models.CharField(help_text='Prix pour les résidents Mauguio/Carnon', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ActivityTimeSlot',
        ),
    ]
