# Generated by Django 5.1.7 on 2025-04-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='ville',
            field=models.CharField(blank=True, choices=[('Mauguio', 'Mauguio'), ('Carnon', 'Carnon'), ('Les deux', 'Mauguio et Carnon')], default='Mauguio', max_length=10),
        ),
    ]
