# Generated by Django 5.1.6 on 2025-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_alter_activitylist_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés spécifiques à cette page séparés par des virgules', max_length=255),
        ),
        migrations.AlterField(
            model_name='activitypage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés spécifiques à cette page séparés par des virgules', max_length=255),
        ),
    ]
