# Generated by Django 5.1.6 on 2025-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_activitypage_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activitypage',
            name='instructors',
        ),
        migrations.AddField(
            model_name='activitypage',
            name='animateurs',
            field=models.ManyToManyField(blank=True, to='activites.animateur'),
        ),
    ]
