# Generated by Django 5.1.7 on 2025-04-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0003_activitypage_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': "Catégorie d'activité",
                'verbose_name_plural': "Catégories d'activités",
            },
        ),
        migrations.AddField(
            model_name='activitypage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activites.activitycategory'),
        ),
    ]
