# Generated by Django 5.1.6 on 2025-03-03 11:30

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0003_animateur_remove_activitypage_instructors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypage',
            name='animateurs',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activites.animateur'),
        ),
    ]
