# Generated by Django 5.1.7 on 2025-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0004_activitycategory_activitypage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypage',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Pour chercher par catégorie dans la liste des activités', related_name='activities', to='activites.activitycategory'),
        ),
    ]
