# Generated by Django 5.1.7 on 2025-04-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0005_alter_activitypage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypage',
            name='ville',
            field=models.CharField(blank=True, choices=[('Mauguio', 'Mauguio'), ('Carnon', 'Carnon'), ('Mauguio et Carnon', 'Mauguio et Carnon')], default='Mauguio', max_length=17),
        ),
    ]
