# Generated by Django 5.1.6 on 2025-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaindexpage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés spécifiques à cette page séparés par des virgules', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés spécifiques à cette page séparés par des virgules', max_length=255),
        ),
        migrations.AlterField(
            model_name='pasteventspage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés spécifiques à cette page séparés par des virgules', max_length=255),
        ),
    ]
