# Generated by Django 5.1.6 on 2025-02-25 09:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendaindexpage_remove_eventpage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='description',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='content',
            field=wagtail.fields.RichTextField(default='', verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, verbose_name='Sous-titre'),
        ),
    ]
