# Generated by Django 5.1.7 on 2025-04-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaindexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='agendaindexpage',
            name='seo_keywords',
        ),
        migrations.DeleteModel(
            name='PastEventsPage',
        ),
    ]
