# Generated by Django 5.1.7 on 2025-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agendaindexpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaindexpage',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agendaindexpage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés spécifiques à cette page séparés par des virgules', max_length=255),
        ),
    ]
