# Generated by Django 5.1.6 on 2025-02-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_eventpage_ville_delete_upcomingeventspage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEventsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'All Events Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date',
            field=models.DateTimeField(help_text="Date et heure de l'événement", verbose_name='Date et heure'),
        ),
    ]
