# Generated by Django 5.1.7 on 2025-04-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_eventpage_ville_agendaindexpage_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaindexpage',
            name='ville',
            field=models.CharField(blank=True, choices=[('Mauguio', 'Mauguio'), ('Carnon', 'Carnon'), ('Mauguio et Carnon', 'Mauguio et Carnon')], max_length=17),
        ),
    ]
