# Generated by Django 5.1.6 on 2025-02-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alleventspage_alter_eventpage_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllEventsPage',
        ),
    ]
