# Generated by Django 5.1.6 on 2025-03-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_remove_eventpage_date_eventpage_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='ville',
            field=models.CharField(choices=[('Mauguio', 'Mauguio'), ('Carnon', 'Carnon'), ('Les deux', 'Mauguio et Carnon')], default='Mauguio', max_length=10),
        ),
    ]
